const Saves = [
  new Save({
    name: '开局档',
    desc: '游戏最开始的样子',
    data: 'eyJkYXRhIjoiMTAiLCJidXlqZCI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJqZG51bSI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJib29zdCI6IjAiLCJib29zdDIiOiIwIiwiUEwxaW5mbyI6IjAiLCJQTDF1bmxvY2siOmZhbHNlLCJQTDF1cGciOltmYWxzZSxmYWxzZSxmYWxzZSxmYWxzZSxmYWxzZSxmYWxzZSxmYWxzZSxmYWxzZV0sImF1dG9idXlqZCI6W2ZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlXSwiYXV0b2Jvb3N0IjpmYWxzZSwiYXV0b2Jvb3N0MiI6ZmFsc2UsInNsaWNlIjoiMCIsInNsaWNldXBnX3JlcCI6WyIwIiwiMCIsIjAiLCIwIl0sInNsaWNldXBnIjpbZmFsc2UsZmFsc2UsZmFsc2UsZmFsc2VdLCJ1bmxvY2tfb3JpZ2luIjpmYWxzZSwib3JpZ2luX2RhdGEiOiIwIiwib3JpZ2luX3VwZyI6WyIwIiwiMCIsIjAiLCIwIiwiMCJdLCJQTDJpbmZvIjoiMCIsIlBMMnVubG9jayI6ZmFsc2UsIlBMMnRtcyI6IjAiLCJidXlzbiI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJzdGFyX25vZGUiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwic3RhciI6IjAiLCJkaW1lbnNpb24iOiIwIiwiYm9vc3QzIjoiMCIsImF1dG9ib29zdDMiOmZhbHNlLCJlbnRyb3B5IjpbIjAiLCIwIiwiMCIsIjAiXSwib3BlbmVudHJvcHkiOmZhbHNlLCJQTDJ1cGciOltmYWxzZSxmYWxzZSxmYWxzZSxmYWxzZV0sImdvZHN0YXIiOiIwIiwiZ29kbm9kZSI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJidXlnbiI6WyIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCJdLCJnbnVubG9jayI6W2ZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlLGZhbHNlXSwicGVybXVwZyI6W10sImNoYWxjb21wIjoiMCIsIm9wZW5jaGFsIjpmYWxzZSwiY2hhbHBhcmEiOltmYWxzZV0sImFjaCI6W119',
    author: '0100000a7',
    id: 0
  }),
]
for (let i=0;i<Saves.length;i++)document.getElementById('saves').innerHTML += Saves[i].toFormat()